#ifndef GL_ATTRIBUTES_H
#define GL_ATTRIBUTES_H

#define ATTRIBUTE_POSITION  0
#define ATTRIBUTE_NORMAL    1
#define ATTRIBUTE_TANGENT   2
#define ATTRIBUTE_BITANGENT 3
#define ATTRIBUTE_TEXCOORD  4

#endif